language: python
python:
  - 3.7
cache:
  pip: true
_ahjhj: &shared_jobs
  script: echo "shared script config"
jobs:
  include:
  - name: Job 1
    <<: *shared_jobs
  - name: Job 2
    <<: *shared_jobs