dist: xenial
language: python
python:
- '3.7'
env:
  global:
  - TRAVIS_SCRIPT_PLACE="$TRAVIS_BUILD_DIR/travis_ci"
  - PIP_CACHE_DIR="$HOME/.cache/pip"
  # - AWS_ACCESS_KEY_ID_DEV="AKIAW4ETJG7LP7R6LLTT"
  - AWS_ACCESS_KEY_ID_DEV="AKIA26LYMRGJU2ZTARFJ"

  - AWS_ACCESS_KEY_ID_STG="AKIAUCVX4DZNBCOZFKDX"
  - AWS_ACCESS_KEY_ID_PRD="AKIA2P73VQJDJ2PSXTSK"
  # AWS_SECRET_ACCESS_KEY_DEV
  # - secure: XJwFcsXrpRrHE5pgkkJGo5TH7U4Y5SCnD79jcRSG3f4+4qPKi/73vgi5vU2OLs6jm3VAKTDpz/g6KgBy/QkCmMncdif1wpAY3Pqj5+R8brr/GIxsGS1E8soTX3uGA8PDU89cIi5OELaOTI/j1GYyl4YRyvSKh5/gFBCA/qPiu7+Z3C9DyEWiOI8lVU4jE/zi7MarN6+SD2FOn1ha6ut6GhHS/VmUjX0oVaC7YvdEuK1oQRxQp1fECyDplPlrLbF0pc/LcUgAKOcfOueq9tGPixH+qEufLBGbtAVivO7U68J/AVsx1GslRC6luKIbJt+AT7+A2tTpg8SAreDtwlEgp7z9e4uLeNguP/cfBZGbBOcPgGcSpih+JjBCF5+5+O2Y190iYanj+tX+fjdwDQyVx4SOS3U6SV8twXtFR0SinjUDFFyj6MK349/6nCT2II5oZN+lr691kfFaoKLPTK6pf3pgJmF6rMeD9s8VSSFXt6Pfb4UHsdWd7muQfCCIH1pRLaQajKbDdIKDGYTyY8M+fcczsw4eCfMMGp8K2cuVjc9ty5IFoVK0bssTlc+8kR3aM087E7hkj6tCDMlLIn/QJpS7tpClpfk/cUM4dCPhNHpdafVzXNPkufCXypazimmkpLY7QxjHgMLC3QHU3UCL+EQXE7eWbHNNd7Y9dOhs/qo=
  - secure: qUm7juZ+o/Rj2xT1o0Gqe2GmCeVUI1d3m31oMNGqbvRx6ldNydTzjrhuEp95kcmPfPbuCELyKNnpTbbgO0YPsiiSRIyUz6Rwg5DxXgIp9TYFpsIGEnDBydqfNfKvW/4nqTJmculT8IzDdhiTlOzzGJKJUJQ4Iv1MG/43HHVMhqjUGbe2vsPKyVvaz6hL1rsaCrTnefMiQE+IMK/oJiGw6pm7BQMHD2yCqAoxBbJ/hq0DhsiXRYTQNXPxoSNn4af9AZcGB4c5XY2sSWxdHGCrP5tucXPQRoIZ6EQdwWT7gejTAhvbLy0SGulPHJmBMP1lx6Lc1tTE35fzGXhArwk6XfbTY/6hyei54lppP/2/VWx+NvP0tF3+DhGn33TT97sRADFHmHDcWoF5WpexqI20P/uJEyVGlCvuNauPgwwE/MupT3Nlz4FkmlOL0kCXhFYtqR12NQFdQPGGVhXjEPTeYfHGv7cDLmGcA9fPNeJsBLAQD0WpR48SEvE/DEr+FFGTLG1i/9QJrDnC+EWr4guFWTwOvXmv4ZtTSxkIGfKI/5cZWcqva31EtWed6otCGdsJEHgmWnyY6FfGUofvrE9EduCFodYY5o0NvbNBujzfVebwbiTgjVd70FNdkrlknP9sbT4hC+LKXeT9nGgFQHlh53yWH72RLLh3MSExTnCVCe8=
  # AWS_SECRET_ACCESS_KEY_STG
  - secure: dYyVWosTbEbTNZLe7h51mNdcRch5aW/X+Y1lOPkiyQ9Ta4tDV0CoP4M5EL1Ua5fpvVNsbDnFiNe4OrQ48n8ER7PzDVa5npkxZYjUkLgK156AAgIaG2+Gtw84CRbrGU1UaqJyGVWp9m81H622bxvtBhaHZNe5kPRmjVE4/pPVQuG+NVMQqL4jSlzf5xWYhWG8BIY7zOBLLsPucefmM27rczCFrb61vIl9WNl7FEGHIdOXMMbihOLXv8f5cNUahfOH6c90pKV401654OU1gQ920lsmC2wwlqu6MU0DB64Z5oow9ME896tr/GSe5Jmf/p/Q+t7sXMW7CoLGvD7i6ok5zlupwqlG3EFqmaC2vcn9F7YKQ8XOPbPp9j/oCHWD4CtmnaU6dHs3ve7p3CLzTqdKwcCtk2KvwbZZNY9QEZSCYvZtozQCuBkUbeaSUTtHag8tbPQBmYIEnGewfKgtLUXjh9XrHhOs7pd0bfG45yUPemaYO8p1YG4+148HGFsOiJy4qvPLSEUT4zfE8X6uDDnOS5yW56t2EUmII945FkF1V//OSm8NwiISjYIrcAqlhIvItr4WeC5AzCktvPx6sCRHQFeRecgs4ne8CDGefxBIwQmY5oal8YEkyZP19yGCr2q+NUlQnVItZ3xza2awlL/iSpyK7jB7d8XagKc9pu+QLX4=
  # AWS_SECRET_ACCESS_KEY_PRD
  - secure: F1iP6OeaT00NQ0YN5VZKc497PdBICo65Cqyq9PTKvl+9zw/g95NWYfqNgpYFgII37/h9aAa61BIaH8z4vosm3EJPo/Uvr5s2fcTOdo60jBd6WG2onKZ5DVqb2n0pRiVc86k3uOGkZIcOIMzzzROKBYK4o+AkopqaBWAjMEj1Xu18Dnyf1jXSAo4EIr6bEPJKcTJb/jPyLjoU1kz/hPivciGAKPwkFSkLBeXRiDEu6DX88ykm+Sk98usZfZGWKFa6uLjV12Ao/UDGnBTcR7VGeeotS06ua0N6jTWcpDrpZ1PRofVDbZS5ELaywMclTYhpY2HVBMxxZOCl8RjYZ/2EA/o8bN5SWkWf16xFJVdZPMcMY5inDFaHTi6iWLt+1pHtt1QytPodRvotPvi9gX951frj1Wx6G1Qgr3xn+rEI4QaRvEQ7azIT8WzzIMR6QZEJeEqqA01oeU6mh+cltVFUzmwo3TA06Fw/M4PANRpRxUOfCDgYmml+qKTroBC/1GYnMJDdVnl19QObLIFhWHpiFL1R/zFXyJWVO0co6aneZm0QaPEmVSZQX9al3NgUZcRhVEwlh/mabAAan5vBQ/UI7+oyRJSOBJyUz214kgJehHyOBGCdskBjDBnUPHFYu8oQ8jyhyLU57WZajfYIbyby/9XDHtw+MXwxtNqdlnULDfg=
if: type = push
cache:
  pip: true
# install:
# - ". ./travis_ci/environment/install_awscli.sh"
jobs:
  include:
  - stage: deploy_dev
    if: branch = develop
    env:
    - ENV="dev"
    - DEPLOY_S3_SRC_DIR="./src"
    - DEPLOY_S3_BUCKET="smartpass-private-static-dev"
    - DEPLOY_S3_OPTIONS="--delete"
    script:
    - echo "DEPLOY CODE TO PRIVATE S3 BUCKET DEV"
    # - ". ./travis_ci/deploy_s3/sync_code_s3.sh"
    # deploy:
    #   provider: s3
    #   access_key_id: $AWS_ACCESS_KEY_ID
    #   secret_access_key: $AWS_SECRET_ACCESS_KEY
    #   bucket: $DEPLOY_S3_BUCKET
    #   skip_cleanup: true
    #   upload-dir: "dev"
    #   local-dir: $DEPLOY_S3_SRC_DIR
    #   region: ap-southeast-1
    #   on:
    #     branch: develop
    notifications:
      slack:
        if: branch = develop
        secure: vdlC68M0W2ZRzsO+wWCYqDb+4HXpvfv1c1aVTw8oPFMknij5rlk/xIe6kPIOlsLlWrnUdpjvjyEoLfi9ajKtWbU3fqn0qj/Ie6fjHYtVfabzG2USrSHGJeTwIOuL3eAvLQzy0C8r4SUrMTOQ/aHCBqbnTmbAzNDOOFGEOjBsEGBSGv+sZbf0D+BfMQeFZEWyz6y+WHLM3Sw0hI62Q3/zHe0kKdDn55JvL55GM6z9E4xG/SArAliMjM+asdo+FNlRxz2/w2nrUjxUOZG4duOyJHHwB2I/Q92YHLcn3gEQYBrCQ9FoQvkebfU9xzauDD5mLhF52YLQLonnECES9UE9AoNJ2A0ESpVfFxiajtl7cE5fVsoAqB5cOc3089G3l8GfrgOYKwV1ri3UVpC1mj+wYhvQP4cuwRGPA+StzBMqK0JDAjV04aBUklq1WwN0njNuhVJJlUkrdskBeqEPQ8cUrmiURumT1uVAM89uhWajjNzrn0VxdmkVHlRqz9hbsLsk/oczzbYO7rn38NXcooX/muR0uhKJVmNALJtIaNkp1MlQcBzXjufLg6Qt7r9dfxpDNlyR9hhM+kkunwc+D9A6SRux/0n397tBYKZkEKWGxEOy0Faw1/UscXBj//6NEzt5bC/dRqxOwMgr5RSYXOgnm/mdgcYFWhOdHgtybTklO+Q=

  - stage: deploy_stg
    if: branch = staging
    env:
    - ENV="stg"
    - DEPLOY_S3_SRC_DIR="./src"
    - DEPLOY_S3_BUCKET="smartpass-private-stg"
    - DEPLOY_S3_OPTIONS="--delete"
    script:
    - echo "DEPLOY CODE TO PRIVATE S3 BUCKET STG"
    # - ". ./travis_ci/deploy_s3/sync_code_s3.sh"
    # deploy:
    #   provider: s3
    #   access_key_id: $AWS_ACCESS_KEY_ID
    #   secret_access_key: $AWS_SECRET_ACCESS_KEY
    #   bucket: $DEPLOY_S3_BUCKET
    #   skip_cleanup: true
    #   upload-dir: "stg"
    #   local-dir: $DEPLOY_S3_SRC_DIR
    #   region: ap-southeast-1
    #   on:
    #     branch: all
    notifications:
      slack:
        if: branch = staging
        secure: NlCztCbxrSuXb8srZmFljE5l0PuQ//36rKhuPANuvR3h3TYl/+HDJ7qoTJCwtjEr6jgS74/0BkHFFQi1Qv5GoJ0dnQRBZ+Ts+s5FFXI2xYXUFbKFroYl0lXADuNgnkF1LJj060PVFNRYgsJd+hzzOd1Oe8+09sZ9mRk015jUafDiu3q23ApvyRYm3p5+DQ3O6Xl3QQVzV2aUZ2vH3iwyoQHx9wpEb8EYk7Qh4x4e4k/6yQR/k4qZyZDlRO+1rQed92KJYTVgPdAK6nPzyluYUwR3rPvCUx2dfcxbI0IuR/rDGTm2wRcsb/OYnBjpFcMTW4RtoP7UKa7he5qcZMEvLF8TFokxfQk8rxFTHzV1CYblMPVG8yshGcLXPfMOMWZcADiTCuGbRYV2mFKApLI0M85Bltu83NhhprSYTfhXSJqGv8SJGhCrSTpvrQeOTjUlRKiZq9a6Zkx7XodwMa4o11poDBAxdi7esszCoIluAJ5++YOt5kEKyxXUBk+9pDWplN0jUQPxpKDhInvobC399cx7Oc3mER4kam2nRbAOE5oHwO2LFD9Np9xXBr/PGBaAHqJ2ECBiQgg6EtKxBoBnL6jpfkHJAgVNhoQncw8IDN+70ecZ091HbX+X7NSb+xj71Waej+NBUEeoyXI0ImFJxv8Dx7vcio1B9XoCaiifIDU=
  - stage: deploy_prd
    if: tag =~ /^v_/
    env:
    - ENV="prd"
    - DEPLOY_S3_SRC_DIR="./src"
    - DEPLOY_S3_BUCKET="smartpass-private-prd"
    - DEPLOY_S3_OPTIONS="--delete"
    script:
    - echo "DEPLOY CODE TO PRIVATE S3 BUCKET PRD"
    - ". ./travis_ci/deploy_s3/sync_code_s3.sh"
    # deploy:
    #   provider: s3
    #   access_key_id: $AWS_ACCESS_KEY_ID
    #   secret_access_key: $AWS_SECRET_ACCESS_KEY
    #   bucket: $DEPLOY_S3_BUCKET
    #   skip_cleanup: true
    #   upload-dir: $TRAVIS_TAG
    #   local-dir: $DEPLOY_S3_SRC_DIR
    #   region: ap-southeast-1
    #   on:
    #     tags: true