rvm:
  - 2.2
  - 2.3

env:
  - FOO=foo BAZ=123
  - FOO=bar BAZ=456

script: 
  - echo $FOO
  - echo $BAZ
  - gem --version

jobs:
  include:
    - script:
      - echo $FOO
      - echo $BAZ
      - gem --version
    - stage: deploy
      script:
        - echo Deploy
        - gem --version
      # Keep in mind to overwrite these here
      rvm: 2.3
      env: FOO=foo