language: python 
python:
  - "3.7"
env:
  - BAZ=10
script: 
  - echo $ENV

jobs:
  include:
    - script:
      - echo $ENV
      - python --version
    - stage: deploy
      script:
        - echo Deploy
        - python --version
        - echo $ENV
      # Keep in mind to overwrite these here
      python: 2.7
      env: FOO=foo